### PR TITLE
Cache obtaining patched index for twemoji

### PR DESCRIPTION
**Pull request by oprypin**
Otherwise this heavy operation (including a large glob and more) runs on every call to 'twemoji'

For `mkdocs build` of mkdocs-material-insiders, this brings the total build time from 6.7s to 4.3s

### CODE REVIEW

**Comment by facelessuser** [comment]
Curious, does MkDocs instantiate multiple Markdown objects or does it create one and reset it each time? If it is the first, is there a reason for that? Normally, the index is should only get built once per Markdown object. I suspect MkDocs is instantiating multiple Markdown objects though.

As far as caching here, I guess there is no problem with it, but but I would think it shouldn't be necessary, but I don't know why or how MkDocs implements everything internally.

**Comment by oprypin** [comment]
Yes, MkDocs instantiates one Markdown object per page.
There is a reason for that, sure. Otherwise things like headers for ToC accumulate across pages, and who knows how many other side effects in various extensions.
Unfortunately most code assumes one Markdown object per page, it's too big of a thing to try to fight.

**Comment by oprypin** [comment]
> most code assumes one Markdown object per page

-that code being *not* in MkDocs itself; if it was just about MkDocs, I could change it quite easily

**Comment by facelessuser** [comment]
Okay, then that explains it. I never verified, but I assumed (wrongly) that the Markdown object was loaded once per site and reset between pages. Obviously, that is not the case. We'll push forward with this though. It will help alleviate build times on large projects.

**Comment by facelessuser** [comment]
Hmm, looks like we have some failures. I'll have to make sure the tip is still passing before I can make any assumptions. Assuming the tip is passing with recent versions of everything, we'll have to address the failures before we can merge.

**Comment by oprypin** [comment]
For sure- I'll look into it in a day

**Comment by facelessuser** [comment]
I fixed tests on the tip. Material exposes Material, Octicons, and FontAwesome icons, but sometimes, the naming convention for some of the icons change. This will break the tests. You should be able to rebase and pick up working tests.

**Comment by oprypin** [comment]
I made a merge via GitHub UI 🙂
Now CI needs to be approved again

**Comment by facelessuser** [comment]
@gir-bot lgtm

**Pull request merged**
